APPLICATION = riot-wrappers-test-mutex
BOARD ?= native
APPLICATION_RUST_MODULE = riot_wrappers_test_mutex
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target

include $(RIOTBASE)/Makefile.include
