[licenses]
version = 2
# We'll generally add license here as long as they're OSI approved, but let's keep an eye on them…
allow = ["Apache-2.0", "BSD-3-Clause", "ISC", "MIT"]
# … and for those, I'd rather doublecheck:
exceptions = [
  { allow = ["LGPL-2.1"], crate = "riot-sys" },
  { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]
private = { ignore = true }
confidence-threshold = 1.0
