# name of your application
APPLICATION = riot-wrappers-test-i2c
APPLICATION_RUST_MODULE = riot_wrappers_test_i2c
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_i2c

include $(RIOTBASE)/Makefile.include
