# name of your application
APPLICATION = riot-wrappers-test-leds
APPLICATION_RUST_MODULE = riot_wrappers_test_leds
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_adc

include $(RIOTBASE)/Makefile.include
