APPLICATION = riot-wrappers-test-pwm
APPLICATION_RUST_MODULE = riot_wrappers_test_pwm
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_pwm

include $(RIOTBASE)/Makefile.include
