# name of your application
APPLICATION = riot-wrappers-test-shell
BOARD ?= native
APPLICATION_RUST_MODULE = riot_wrappers_test_shell
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target

USEMODULE += shell

include $(RIOTBASE)/Makefile.include
