APPLICATION = riot-wrappers-test-spi
APPLICATION_RUST_MODULE = riot_wrappers_test_spi
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_spi
USEMODULE += ztimer_usec

include $(RIOTBASE)/Makefile.include
