# name of your application
APPLICATION = riot-wrappers-test-gpio
APPLICATION_RUST_MODULE = riot_wrappers_test_gpio
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_gpio

include $(RIOTBASE)/Makefile.include
