# name of your application
APPLICATION = riot-wrappers-test-uart
APPLICATION_RUST_MODULE = riot_wrappers_test_uart
BASELIBS += $(APPLICATION_RUST_MODULE).module
FEATURES_REQUIRED += rust_target
FEATURES_REQUIRED += periph_uart

include $(RIOTBASE)/Makefile.include
