# name of your application
APPLICATION = riot-wrappers-test-gnrc-embedded-nal-udp
APPLICATION_RUST_MODULE = riot_wrappers_test_gnrc_embedded_nal_udp

USEMODULE += sock_udp
USEMODULE += gnrc_ipv6

include $(RIOTBASE)/Makefile.include
